'use client';

import { useAuth } from '@/hooks';

const DashboardPage = () => {
 const { user } = useAuth();
 return (
     <div className='text-black'>
      <h1 className='text-2xl font-semibold scroll-smooth focus:scroll-auto'>Bienvenido/a</h1>
         <div>
             <span>{user?.fullName}</span>
             <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat harum iure magni molestias nemo qui ratione sit! Accusantium, beatae consequuntur cum dolor ea eveniet magnam necessitatibus numquam quia temporibus, voluptatum?</span><span>Ab accusantium, alias beatae debitis explicabo harum hic illum ipsum mollitia neque nobis, non officia praesentium quasi quisquam, unde vel! Asperiores exercitationem hic minima nesciunt quisquam quo, veritatis? Aut, distinctio.</span><span>Blanditiis commodi deleniti facilis fuga possimus ratione sunt veniam! Amet, consequatur doloremque iusto minus quam rem. Dignissimos eaque excepturi fuga officiis optio, ut. Beatae doloremque est excepturi pariatur sint voluptas?</span><span>Architecto aspernatur dignissimos eveniet fuga impedit in iste minus necessitatibus, numquam, porro quod rerum sed totam? Architecto et fugiat necessitatibus nulla sit ullam. Doloremque eum magnam quasi qui quo quos.</span><span>Beatae consequatur consequuntur dolorum ea exercitationem perferendis provident saepe vero. Aperiam autem, beatae blanditiis nemo non obcaecati officia, quidem recusandae repellat saepe temporibus vero! Eos fugit odio quas sapiente suscipit?</span><span>At in minus quos tempora velit. Assumenda enim in labore libero magnam nisi quaerat quidem repellat sint voluptate! Assumenda earum eius nam obcaecati pariatur quisquam repellat ullam ut voluptate voluptatum.</span><span>Accusamus ad atque beatae debitis dolor eaque earum et, illum odio pariatur, perspiciatis provident quasi vero. Esse reprehenderit, tenetur? Amet consectetur consequatur earum eum hic maxime natus perferendis quis vitae.</span><span>Ad, architecto consectetur eos molestias omnis recusandae veritatis. Et, officia ullam! Corporis eum eveniet fuga id ipsa iste minus nobis quae vero? Autem ducimus laboriosam modi, nemo quos vero voluptas!</span><span>Aliquam id nemo odio possimus quisquam repellendus saepe! Atque dolorum eius in ipsa perferendis porro quos repellat sit? Assumenda commodi dolorum fuga harum inventore minima molestiae quidem sapiente tempora voluptatem.</span><span>Delectus est fugiat nihil possimus quas quod suscipit. Ab architecto autem consequatur delectus dicta dolorem doloremque inventore ipsum nemo officia, quam quas quasi qui repudiandae, sequi tenetur voluptatibus. Eveniet, temporibus!</span>
             </p>
             <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat harum iure magni molestias nemo qui ratione sit! Accusantium, beatae consequuntur cum dolor ea eveniet magnam necessitatibus numquam quia temporibus, voluptatum?</span><span>Ab accusantium, alias beatae debitis explicabo harum hic illum ipsum mollitia neque nobis, non officia praesentium quasi quisquam, unde vel! Asperiores exercitationem hic minima nesciunt quisquam quo, veritatis? Aut, distinctio.</span><span>Blanditiis commodi deleniti facilis fuga possimus ratione sunt veniam! Amet, consequatur doloremque iusto minus quam rem. Dignissimos eaque excepturi fuga officiis optio, ut. Beatae doloremque est excepturi pariatur sint voluptas?</span><span>Architecto aspernatur dignissimos eveniet fuga impedit in iste minus necessitatibus, numquam, porro quod rerum sed totam? Architecto et fugiat necessitatibus nulla sit ullam. Doloremque eum magnam quasi qui quo quos.</span><span>Beatae consequatur consequuntur dolorum ea exercitationem perferendis provident saepe vero. Aperiam autem, beatae blanditiis nemo non obcaecati officia, quidem recusandae repellat saepe temporibus vero! Eos fugit odio quas sapiente suscipit?</span><span>At in minus quos tempora velit. Assumenda enim in labore libero magnam nisi quaerat quidem repellat sint voluptate! Assumenda earum eius nam obcaecati pariatur quisquam repellat ullam ut voluptate voluptatum.</span><span>Accusamus ad atque beatae debitis dolor eaque earum et, illum odio pariatur, perspiciatis provident quasi vero. Esse reprehenderit, tenetur? Amet consectetur consequatur earum eum hic maxime natus perferendis quis vitae.</span><span>Ad, architecto consectetur eos molestias omnis recusandae veritatis. Et, officia ullam! Corporis eum eveniet fuga id ipsa iste minus nobis quae vero? Autem ducimus laboriosam modi, nemo quos vero voluptas!</span><span>Aliquam id nemo odio possimus quisquam repellendus saepe! Atque dolorum eius in ipsa perferendis porro quos repellat sit? Assumenda commodi dolorum fuga harum inventore minima molestiae quidem sapiente tempora voluptatem.</span><span>Delectus est fugiat nihil possimus quas quod suscipit. Ab architecto autem consequatur delectus dicta dolorem doloremque inventore ipsum nemo officia, quam quas quasi qui repudiandae, sequi tenetur voluptatibus. Eveniet, temporibus!</span>
             </p>
             <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat harum iure magni molestias nemo qui ratione sit! Accusantium, beatae consequuntur cum dolor ea eveniet magnam necessitatibus numquam quia temporibus, voluptatum?</span><span>Ab accusantium, alias beatae debitis explicabo harum hic illum ipsum mollitia neque nobis, non officia praesentium quasi quisquam, unde vel! Asperiores exercitationem hic minima nesciunt quisquam quo, veritatis? Aut, distinctio.</span><span>Blanditiis commodi deleniti facilis fuga possimus ratione sunt veniam! Amet, consequatur doloremque iusto minus quam rem. Dignissimos eaque excepturi fuga officiis optio, ut. Beatae doloremque est excepturi pariatur sint voluptas?</span><span>Architecto aspernatur dignissimos eveniet fuga impedit in iste minus necessitatibus, numquam, porro quod rerum sed totam? Architecto et fugiat necessitatibus nulla sit ullam. Doloremque eum magnam quasi qui quo quos.</span><span>Beatae consequatur consequuntur dolorum ea exercitationem perferendis provident saepe vero. Aperiam autem, beatae blanditiis nemo non obcaecati officia, quidem recusandae repellat saepe temporibus vero! Eos fugit odio quas sapiente suscipit?</span><span>At in minus quos tempora velit. Assumenda enim in labore libero magnam nisi quaerat quidem repellat sint voluptate! Assumenda earum eius nam obcaecati pariatur quisquam repellat ullam ut voluptate voluptatum.</span><span>Accusamus ad atque beatae debitis dolor eaque earum et, illum odio pariatur, perspiciatis provident quasi vero. Esse reprehenderit, tenetur? Amet consectetur consequatur earum eum hic maxime natus perferendis quis vitae.</span><span>Ad, architecto consectetur eos molestias omnis recusandae veritatis. Et, officia ullam! Corporis eum eveniet fuga id ipsa iste minus nobis quae vero? Autem ducimus laboriosam modi, nemo quos vero voluptas!</span><span>Aliquam id nemo odio possimus quisquam repellendus saepe! Atque dolorum eius in ipsa perferendis porro quos repellat sit? Assumenda commodi dolorum fuga harum inventore minima molestiae quidem sapiente tempora voluptatem.</span><span>Delectus est fugiat nihil possimus quas quod suscipit. Ab architecto autem consequatur delectus dicta dolorem doloremque inventore ipsum nemo officia, quam quas quasi qui repudiandae, sequi tenetur voluptatibus. Eveniet, temporibus!</span>
             </p>
             <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat harum iure magni molestias nemo qui ratione sit! Accusantium, beatae consequuntur cum dolor ea eveniet magnam necessitatibus numquam quia temporibus, voluptatum?</span><span>Ab accusantium, alias beatae debitis explicabo harum hic illum ipsum mollitia neque nobis, non officia praesentium quasi quisquam, unde vel! Asperiores exercitationem hic minima nesciunt quisquam quo, veritatis? Aut, distinctio.</span><span>Blanditiis commodi deleniti facilis fuga possimus ratione sunt veniam! Amet, consequatur doloremque iusto minus quam rem. Dignissimos eaque excepturi fuga officiis optio, ut. Beatae doloremque est excepturi pariatur sint voluptas?</span><span>Architecto aspernatur dignissimos eveniet fuga impedit in iste minus necessitatibus, numquam, porro quod rerum sed totam? Architecto et fugiat necessitatibus nulla sit ullam. Doloremque eum magnam quasi qui quo quos.</span><span>Beatae consequatur consequuntur dolorum ea exercitationem perferendis provident saepe vero. Aperiam autem, beatae blanditiis nemo non obcaecati officia, quidem recusandae repellat saepe temporibus vero! Eos fugit odio quas sapiente suscipit?</span><span>At in minus quos tempora velit. Assumenda enim in labore libero magnam nisi quaerat quidem repellat sint voluptate! Assumenda earum eius nam obcaecati pariatur quisquam repellat ullam ut voluptate voluptatum.</span><span>Accusamus ad atque beatae debitis dolor eaque earum et, illum odio pariatur, perspiciatis provident quasi vero. Esse reprehenderit, tenetur? Amet consectetur consequatur earum eum hic maxime natus perferendis quis vitae.</span><span>Ad, architecto consectetur eos molestias omnis recusandae veritatis. Et, officia ullam! Corporis eum eveniet fuga id ipsa iste minus nobis quae vero? Autem ducimus laboriosam modi, nemo quos vero voluptas!</span><span>Aliquam id nemo odio possimus quisquam repellendus saepe! Atque dolorum eius in ipsa perferendis porro quos repellat sit? Assumenda commodi dolorum fuga harum inventore minima molestiae quidem sapiente tempora voluptatem.</span><span>Delectus est fugiat nihil possimus quas quod suscipit. Ab architecto autem consequatur delectus dicta dolorem doloremque inventore ipsum nemo officia, quam quas quasi qui repudiandae, sequi tenetur voluptatibus. Eveniet, temporibus!</span>
             </p>
         </div>
     </div>
 );
};

export default DashboardPage;
